# Generated by Django 4.1.7 on 2023-03-27 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_disc_category_ser_alter_reminder_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='ser',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 27, 15, 24, 14, 608053, tzinfo=datetime.timezone.utc)),
        ),
    ]
